sudo: required
language: C
services:
 - docker
addons:
  apt:
    packages:
    - python-nose2
script:
 - mv builds/app.docker Dockerfile
 - docker build -t app .
 - mv builds/nginx.docker Dockerfile
 - docker build -t nginx .
 - nose2