sudo: required
language: C
services:
 - docker
addons:
  apt:
    packages:
    - python-nose2
    - python-pip
before_script:
 - sudo pip install -r delegito/requirements.txt
script:
 - docker build -t api delegito
 - docker build -t proxy interface
 - python setup.py build
 - python setup.py test
 - sudo python setup.py install