sudo: required
language: C
services:
 - docker
addons:
  apt:
    packages:
    - python-nose2
    - python-pip
before_script:
 - pip install delegito/requirements.txt
script:
 - docker build -t api delegito
 - docker build -t proxy interface
 - cd delegito && nose2 tests